<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>NgpbLauncher</AssemblyName>
    <Version>1.2.0</Version>
    <Company>Next Generation Point Blank</Company>
    <Product>NGPB Launcher Enterprise</Product>
    <StartupObject>NgpbLauncher.Program</StartupObject>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CS8604;CS8602;CS8618</NoWarn>
    
    <!-- MATIKAN DI CSPROJ, AKTIFKAN VIA CLI DI WORKFLOW -->
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="**\*.xaml" SubType="Designer" Generator="MSBuild:Compile" Exclude="bin\**;obj\**" />
    <None Remove="Assets\**\*" />
    <Resource Include="Assets\**\*" Condition="Exists('Assets\%(RecursiveDir)%(Filename)%(Extension)')" />
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>
</Project>
